### ISSUE TITLE
undefined method `openai_access_key=' for an instance of Eyeloupe::Configuration

### ISSUE THREAD

**Issue by brandonzylstra** [alxlion/eyeloupe#6]
When trying to start up Rails with almost the same configuration as the README

```
Eyeloupe.configure do |config|
  config.excluded_paths = %w[assets favicon.ico manifest.json]
  config.capture = Rails.env.development?
  config.openai_access_key = ENV['OPENAI_EYELOUPE_KEY']
  config.openai_model = "gpt-4"
  config.database = 'eyeloupe'
end
```

I get the following error:

```
/Users/brandon/Code/Rails/portal/config/initializers/eyeloupe.rb:6:in `block in <top (required)>': undefined method `openai_access_key=' for an instance of Eyeloupe::Configuration (NoMethodError)
```

The same thing happens for the next line:

```
/Users/brandon/Code/Rails/portal/config/initializers/eyeloupe.rb:6:in `block in <top (required)>': undefined method `openai_model=' for an instance of Eyeloupe::Configuration (NoMethodError)
```

And for the last line:

```
/Users/brandon/Code/Rails/portal/config/initializers/eyeloupe.rb:7:in `block in <top (required)>': undefined method `database=' for an instance of Eyeloupe::Configuration (NoMethodError)
```

**Comment by brandonzylstra** [comment]
For some reason just adding 

```
gem "eyeloupe"
```

to my Gemfile gave me version 0.2.0.  Once I changed that to 

```
gem "eyeloupe", ">= 0.4.0"
```

and did a `bundle update eyeloupe`, it seems to work now.  I don't know what would cause me to be given an older version at first.
